name: Daily Commit Automation

on:
  schedule:
    # Runs every day at 2 AM UTC (adjust as needed)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Status (23f3002091@ds.study.iitm.ac.in)
        run: |
          echo "Last updated: $(date)" > last_updated.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_updated.txt
          git commit -m "Automated update: $(date)"
          git push
